version: '3'

services:
  web:
    image: 192.168.99.105:5000/stack-demo:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
  redis:
    image: redis:alpine
    networks:
      - webnet
networks:
  webnet:
